### ISSUE TITLE
Matrix items won't expand in Safari

### ISSUE THREAD

**Issue by flannelinc** [necoapps/craft-matrix-snap#1] opened 2023-05-30 23:53 UTC
Matrix items do not expand in Safari v16.3

**Comment by chrisjbr** [comment] 2023-06-08 20:31
Thanks for flagging this. I can't recreate the issue on my end, although my version of Safari is slightly newer (v16.4).

- Are there any errors in the browser console when you try to toggle a block?
- Are there any other Craft plugins running? If so, which ones?

**Comment by flannelinc** [comment] 2023-10-13 23:25
Sorry for the slow response. I am seeing this error in the console:
`TypeError: undefined is not an object (evaluating 'a.data("block").$actionMenu')`

Below are all of the plugins being used in this system:
Code Field
Color Mixer
Control Panel Nav
Expanded Singles
Field Manager
Formie
Google Maps
Mailgun
Redactor
SEOMatic
Super Table
Typed Link field
Wordsmith
oEmbed

Thank you for looking into this. I really love this idea and would like to use it. This should be native functionality in Craft, IMO. Also, for what it's worth, it only works intermittently on Chrome. Sometimes it works right away and other times I have to click out of the entry and back in.

**Comment by chrisjbr** [comment] 2023-10-18 22:06
No problem, thanks for the feedback! And for providing the list of plugins.

I have a couple more questions if that's okay:

- In your matrix, does the cog icon in the titlebar reveal a menu when clicked? Do the Expand and Collapse actions work when clicked? These are what Matrix Snap leverages.
- What version of Craft are you running?

**Comment by flannelinc** [comment] 2023-10-18 23:11
1. Yes, collapse and expand works in all browsers, including if I select all blocks and I can collapse/expand all at once.
2. The latest: Craft 4.5.7

**Comment by chrisjbr** [comment] 2023-10-19 21:20
Good to know, thanks.

I can't recreate the error in the default mode (when the entry screen loads), however, if you're referring to the revision mode, I can recreate what you're describing - I've just released a fix.

Could you try updating Matrix Snap within your Craft CMS environment and let me know if this helps? (Note, matrix blocks can't be toggled in revision mode by design from Craft, but with the Matrix Snap update, the blocks shouldn't appear "broken" and the console error should be gone)

**Comment by flannelinc** [comment] 2023-11-30 00:48
I have an update for you. I hate to say this, but I have narrowed this issue down to a single page in the default site on my multi-site system. It's a sample page where I have 12 Matrix blocks as an example of what each looks like. Every other entry on every other site, Matrix Snap works perfectly. So, is this an issue of the plugin locking up when there are many blocks or is this some weird isolated bug with that specific entry? Unless this happens again on a different entry, I will chalk this up to an isolated incident. Thank you for all of your effort looking into this.

**Comment by phofm** [comment] 2024-02-20 15:26
I’ll jump onto this, even though my client is experiencing this with Firefox. The whole thing was working fine until it didn’t and we aren’t able to pinpoint the changes that cause this. 

We have pages where our client can add various matrix blocks. The error of not being able to expand these fields sometimes occurs on pages where there are more than 40 `.matrix-block`-nodes but sometimes a page with more than 90 loads fine. So it doesn’t have anything to do with the number of `.matrix-block`-nodes.

When it happens we get this error: `Uncaught TypeError: t.data(...) is undefined`

So it appears to be some sort of timing issue, where `$(".matrixblock")` does not select anything. Our (somewhat crude) workaround was to use a custom plugin to add a button to the pages, which when clicked runs this code from matrix-snap:

```
        $(".matrixblock").each(
          function () {
            var t = $(this),
            a = t.data("block").$actionMenu;
            $("a[data-action=collapse]", a).click(),
            setTimeout(function () {
              t.removeClass("is-faux-collapsed")
            }, 200)
          }
        )
```

Not an ideal solution, but for our client it’s better than having to work with the standard Craft CMS functionality of expanded matrix fields.

Maybe this helps in any way troubleshooting the problem. If there’s any information we can provide to help, let us know.

---
Versions:
Craft 4.7.3
Matrix Snap 1.0.2
Control Panel CSS 2.6.0
Do It Yourself widget 3.0.0
Redactor 3.0.4

**Comment by flannelinc** [comment] 2024-02-20 19:55
@phofm, thanks for adding your experience. Hopefully it helps the dev team to find the issue. 

Update: For a while I thought that is was just that one page/site, but the issue started popping up everywhere I used it. I finally had to remove the plugin. The functionality is exactly what I've been looking for, but it just became too buggy.

I will continue to follow this thread hoping for a fix one day!

**Comment by chrisjbr** [comment] 2024-02-22 18:06
Hi @flannelinc, sorry for the delay in my response, and @phofm, thank you for chiming in, especially for sharing your workaround and insight.

I think you are right, something is off with the timing. I had to pick this apart to recreate the issue as I just couldn't replicate it on my end. It seems that usually, Matrix Snap has the matrix data it needs to operate, but other times, matrix blocks take a little longer to initialise, so Matrix Snap can't retrieve what it needs to expand the blocks.

Your workaround kicks things into gear because by the time you (or your client) clicks the button, the matrix block data has initialised, so Matrix Block can function as intended. This is what confirmed to me your suspicion of a timing issue. Thanks again for sharing this, it was super helpful.

I'm working on a fix, it's looking promising but I'll continue to test and hopefully have a new version available by the end of the week. Hopefully I've got it this time!

**Comment by flannelinc** [comment] 2024-02-22 19:42
This is great news. Thank you!

**Comment by chrisjbr** [comment] 2024-02-25 20:12
Hi again, as promised, a new version has been released. Please try out Matrix Snap v1.0.3 which, all being well, fixes this bug 🙂

**Comment by flannelinc** [comment] 2024-02-27 02:54
Fantastic... thank you! I'll report back if I see any issues.

**Comment by phofm** [comment] 2024-02-29 09:19
> Hi again, as promised, a new version has been released. Please try out Matrix Snap v1.0.3 which, all being well, fixes this bug 🙂

Excellent! That appears to have fixed the problem. I’ll be in touch it happens again. Thank you so much for your quick response!

**Comment by chrisjbr** [comment] 2024-02-29 23:38
No problem, thank you both for your help in the raising and resolving of this bug!

**Closed as completed by chrisjbr** 2024-02-29 23:38 UTC
